title: Rohin Daswani
email: rohindaswani@gmail.com
description: >
  I am a Curious Technologist. What is that you ask? I am Full-Stack Software Engineer with wide ranging interests some of which include art, food and policy. Coloring calms me, sichuan food energizes me and the Indian Political Economy intrigues me.
baseurl: ""
url: "https://rohindaswani.github.io"

owner: "rohin daswani"
email: "rohindaswani@g h mail dot com"
facebook_username: "rohin.daswani"
twitter_username: "@RohinDaswani1"
github_username: "rohindaswani"
#address:
#  - line:
#  - line:
#telephone:
copyright: rohindaswani

# API settings
google_api_key:

# Build settings
markdown: kramdown
